name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Trust developer certificate
      run: dotnet dev-certs https --verbose --trust

    - name: Install .NET Aspire workload
      run: dotnet workload install aspire

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    
    - name: Pack
      run: |
        dotnet pack src/FirebirdResources.Testcontainers/FirebirdResources.Testcontainers.csproj -c Release -o packages
        dotnet pack src/FirebirdResources.HealthChecks/FirebirdResources.HealthChecks.csproj -c Release -o packages
    
    - name: Push to NuGet
      run: dotnet nuget push "packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: packages/*.nupkg
        generate_release_notes: true